Copy user provided plugins into the GLPI source at runtime

diff --git a/root/etc/cont-init.d/50-config b/root/etc/cont-init.d/50-config
--- a/root/etc/cont-init.d/50-config
+++ b/root/etc/cont-init.d/50-config
@@ -14,6 +14,7 @@ fi
 mkdir -p \
     /config/glpi-config \
     /config/glpi-files \
+    /config/glpi-marketplace \
     /config/glpi-log
 
 PREV_DIR=$(pwd)
@@ -64,3 +65,13 @@ if [ ! -z ${APP_URL+x} ]; then
   REPLACE_URL=$(echo ${APP_URL} | awk -F/ '{print $3}')
 fi
 sed -i "s/APP_URL_PLACEHOLDER/${REPLACE_URL}/g" /config/nginx/site-confs/default
+
+# Install plugins from user config into the GLPI framework
+# This is required because the PHP FPM resolves symlinks, the following fails at runtime; /var/www/html/marketplace -> /config/glpi-marketplace
+# NOTE; Folder glpi-marketplace might not exist
+cd /config/glpi-marketplace || exit
+shopt -s globstar nullglob
+for i in *; do
+  [[ -e "/var/www/html/marketplace/${i}" ]] && rm -rf "/var/www/html/marketplace/${i}"
+  cp -r "${i}" "/var/www/html/marketplace/${i}"
+done
